name: dart_console_openapi
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  dio: ^5.0.0
  built_value: ^8.1.0
  built_collection: ^5.1.1
  openapi:
    path: ./client

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.1.7
  built_value_generator: ^8.1.0
  json_serializable: ^6.1.4
